### ISSUE TITLE
found some error when build using "npm run dev"

### ISSUE THREAD

**Issue by sseen** [htr3n/htr3n-blog#1]
When I entered this command, I found some errors.
 How can I solve it?
```
$ npm run dev
npm ERR! missing script: dev
npm ERR! A complete log of this run can be found in:
```

**Comment by htr3n** [comment]
@sseen thanks for reporting the error. I forgot the update the documentation in README.

**Comment by htr3n** [comment]
Please refer to the updated README and let me know whether these issues still exist. Thanks
