### ISSUE TITLE
Code blocks do not line wrap

### ISSUE THREAD

**Issue by tomodachi94** [htr3n/htr3n-blog#18]
Code blocks do not line wrap on longer lines, causing it to run out of the box and be barely-visible. Here's an example from your ["Faster Zsh"](https://htr3n.github.io/2018/07/faster-zsh/#organising-shell-startup-order) article:

![image](https://github.com/htr3n/htr3n-blog/assets/68489118/dbe71a97-65cf-4dc9-8302-9c169fc0d819)

**Comment by htr3n** [comment]
@tomodachi94 thanks for raising this. You are right, it's the code highlighting library does not recognize the block for Zshell `zsh`, when I change from zsh to sh, the code wraps properly.
